### ISSUE TITLE
Connection refused error for FOSv9.1.1b

### ISSUE THREAD

**Issue by autocoder10** [brocade/ansible#151]
Hello, I'm trying to configure the new ED-DCX7-4B switch (FOS v9.1.1b) with the Ansible but I'm seeing the below error for below task using default admin acc. The same code works fine with FOS v9.0.x. Please review and let me know how to fix this error.

Testing with both Brocade FOS collection 1.3.0 and 1.3.3. 

Note: No HTTPS certs installed. So mentioned https as false in the playbook.

**Code**
  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: admin
      fos_password: "{{ ansible_password }}"
      **https: False**

tasks:
  - name: Gather FC switch facts-2
    brocade_facts:
      credential: "{{credential}}"
      vfid: -1
      gather_subset:
        - brocade_fibrechannel_switch
    register: resultsnew1

**Error:**
TASK [Gather FC switch facts-2] ************************************************
task path: /runner/project/Test_incubationconfig.yml:129
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib64/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib64/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib64/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1710780108.4955573-20-37779755342325/AnsiballZ_brocade_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1710780108.4955573-20-37779755342325/AnsiballZ_brocade_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1710780108.4955573-20-37779755342325/AnsiballZ_brocade_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.brocade_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py", line 592, in <module>
  File "/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py", line 270, in main
  File "/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_connection.py", line 56, in login
  File "/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_url.py", line 245, in url_helper
  File "/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py", line 1384, in open_url
  File "/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py", line 1294, in open
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
fatal: [newswitch1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/usr/lib64/python3.8/urllib/request.py\\", line 1354, in do_open\\n    h.request(req.get_method(), req.selector, req.data, headers,\\n  File \\"/usr/lib64/python3.8/http/client.py\\", line 1256, in request\\n    self._send_request(method, url, body, headers, encode_chunked)\\n  File \\"/usr/lib64/python3.8/http/client.py\\", line 1302, in _send_request\\n    self.endheaders(body, encode_chunked=encode_chunked)\\n  File \\"/usr/lib64/python3.8/http/client.py\\", line 1251, in endheaders\\n    self._send_output(message_body, encode_chunked=encode_chunked)\\n  File \\"/usr/lib64/python3.8/http/client.py\\", line 1011, in _send_output\\n    self.send(msg)\\n  File \\"/usr/lib64/python3.8/http/client.py\\", line 951, in send\\n    self.connect()\\n  File \\"/usr/lib64/python3.8/http/client.py\\", line 922, in connect\\n    self.sock = self._create_connection(\\n  File \\"/usr/lib64/python3.8/socket.py\\", line 808, in create_connection\\n    raise err\\n  File \\"/usr/lib64/python3.8/socket.py\\", line 796, in create_connection\\n    sock.connect(sa)\\nConnectionRefusedError: [Errno 111] Connection refused\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\"/root/.ansible/tmp/ansible-tmp-1710780108.4955573-20-37779755342325/AnsiballZ_brocade_facts.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/root/.ansible/tmp/ansible-tmp-1710780108.4955573-20-37779755342325/AnsiballZ_brocade_facts.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/root/.ansible/tmp/ansible-tmp-1710780108.4955573-20-37779755342325/AnsiballZ_brocade_facts.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.brocade_facts', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 207, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 97, in _run_module_code\\n    _run_code(code, mod_globals, init_globals,\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 87, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\\", line 592, in <module>\\n  File \\"/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/modules/brocade_facts.py\\", line 270, in main\\n  File \\"/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_connection.py\\", line 56, in login\\n  File \\"/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/brocade_url.py\\", line 245, in url_helper\\n  File \\"/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\\", line 1384, in open_url\\n  File \\"/tmp/ansible_brocade_facts_payload_nxjt_i9z/ansible_brocade_facts_payload.zip/ansible/module_utils/urls.py\\", line 1294, in open\\n  File \\"/usr/lib64/python3.8/urllib/request.py\\", line 222, in urlopen\\n    return opener.open(url, data, timeout)\\n  File \\"/usr/lib64/python3.8/urllib/request.py\\", line 525, in open\\n    response = self._open(req, data)\\n  File \\"/usr/lib64/python3.8/urllib/request.py\\", line 542, in _open\\n    result = self._call_chain(self.handle_open, protocol, protocol +\\n  File \\"/usr/lib64/python3.8/urllib/request.py\\", line 502, in _call_chain\\n    result = func(*args)\\n  File \\"/usr/lib64/python3.8/urllib/request.py\\", line 1383, in http_open\\n    return self.do_open(http.client.HTTPConnection, req)\\n  File \\"/usr/lib64/python3.8/urllib/request.py\\", line 1357, in do_open\\n    raise URLError(err)\\nurllib.error.URLError: <urlopen error [Errno 111] Connection refused>\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
newswitch1              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

sw0:FID128:admin> firmwareshow 
Slot Name       Appl     Primary/Secondary Versions               Status
--------------------------------------------------------------------------
  1  CP0        FOS      v9.1.1b                                  ACTIVE *
                                 v9.1.1b                                  
  2  CP1        FOS      v9.1.1b                                  STANDBY
                                 v9.1.1b                                  
sw0:FID128:admin> 

sw0:FID128:admin> mgmtapp --show
  REST Configuration:
        Interface State: Enabled 
        **Effective Protocol: HTTP only**
        HTTP State: Enabled
        Session Count: 3
  HTTPS Configuration:
        KeepAlive : Disabled
        KeepAliveTimeout : 15sec

**Comment by autocoder10** [comment]
Found out that TCP port 80 is set to deny under ipfilter policy. Fixed it and looks good now.
